### ISSUE TITLE
is that library affected by the places API changes google is doing?

### ISSUE THREAD

**Issue by DennyWeinberg** [Mindinventory/vanilla-place-picker#18]
> Google has deprecated the place picker and will be removing it completely, please do not use Place picker in your project and more

I just want to have a place picker. I don't even need autocomplete.

**Comment by xyzvoyager** [comment]
@DennyWeinberg This library is made after Google did changes to the Places API and deprecated the Place Picker, It is alternative to Place Picker and yes you can have simple picker with map, without autocomplete, we have that option for you.

**Comment by DennyWeinberg** [comment]
Nice! Would it be 100% free of charge without autocomplete and nearby places?
(Just the default maps usage that we can't avoid)

**Comment by xyzvoyager** [comment]
@DennyWeinberg there are limits to number of API calls you can make, check official docs for that. it  won't work just like that, you have to add the API key and other stuff.

**Comment by DennyWeinberg** [comment]
Thanks! I will try that. I'm replacing my picker in my "Photo Map" apps, just for your information  :)
