### ISSUE TITLE
Show selected location from autoComplete in map

### ISSUE THREAD

**Issue by abhimuktheeswarar** [Mindinventory/vanilla-place-picker#22]
When we open auto-complete from map picker, it will be great if u give an option to show the location in the map when selecting from the auto-complete suggestion before delivery it to the intent.

**Comment by MahmoudiOussama** [comment]
We will deeply appreciate if the project owner implement the feature @abeemukthees mentioned.

**Comment by akashmi** [comment]
@abeemukthees @MahmoudiOussama 
Thanks for your valuable suggestion. we will include it in our next updates.

**Comment by akashmi** [comment]
@abeemukthees @MahmoudiOussama 
We have added future as you requested.

**Comment by MahmoudiOussama** [comment]
@akashmi Thank you so much Sir, thank you for your time.
I tested it, it works perfect.
