### ISSUE TITLE
Pick button is obstructed in full screen phones

### ISSUE THREAD

**Issue by quantyam** [Mindinventory/vanilla-place-picker#23]
When starting 
 Intent intent = (new VanillaPlacePicker.Builder(Add_Property.this).setTintColor(R.color.colorAccent).enableSatelliteView(true).with(PickerType.MAP).build());

                            startActivityForResult(intent, 100);

The activity starts in full screen, on full screen phones such as S10 Plus , the pick button is behind the fron camera and cannot be clicked.

**Comment by malikmotani** [comment]
@quantyam Can you please share more details? 
If you are using full-screen activity please refer [display-cutout](https://developer.android.com/guide/topics/display-cutout)

**Comment by akashmi** [comment]
As didn't received more details from users. and it's seems working here. closing this issue.
