### ISSUE TITLE
auto-complete UI should use the Android places SDK

### ISSUE THREAD

**Issue by ericytsang** [Mindinventory/vanilla-place-picker#28]
to allow restricting API key usage to authorized apps to prevent/minimize unauthorized usage of our Google Map API keys, auto-complete UI
* should use [Places SDK for Android](https://developers.google.com/places/android-sdk/start)
    * should use the [new Places SDK for Android](https://developers.google.com/places/android-sdk/client-migration)
* instead of [Places REST API](https://developers.google.com/places/web-service/intro)

when i restricted my api key to only allow requests from my app
* while using the auto-complete activity, i got the error message `This IP, site or mobile application is not authorized to use this API key.`.
* the map UI still works as expected though.

when investigating the code, i see that:
* we are using the Places REST API via a web client
    * this is causing Google to reject my API requests because
        * they are "Places REST API web requests"
        * instead of requests made from the Places SDK for Android

**Comment by malikmotani** [comment]
Implemented new Google places SDK in [release 0.0.9](https://github.com/Mindinventory/vanilla-place-picker/releases/tag/0.0.9)
