### ISSUE TITLE
issue with MAP_WITH_AUTO_COMPLETE in java

### ISSUE THREAD

**Issue by g2dgaming** [Mindinventory/vanilla-place-picker#37]
LatLngBounds.Builder builder = new LatLngBounds.Builder();
                builder.include(new LatLng(bottomCoordinate,leftCoordinate)).include(new LatLng(topCoordinate,rightCoordinate));
                LatLngBounds cityBounds=builder.build();
                Intent locationPickerIntent = new VanillaPlacePicker.Builder(OrderActivity.this)
                        .withLocation(cityLatitude,cityLongitude)
                        .with(PickerType.MAP)
                        .setPickerLanguage(PickerLanguage.ENGLISH)
                        .setLocationRestriction(cityBounds.northeast,cityBounds.southwest)
                        .setCountry("IN")
                        .enableShowMapAfterSearchResult(true)
                        .setMapType(MapType.NORMAL)
                        .setMapPinDrawable(R.drawable.ic_placeholder)
                        .build();
                startActivityForResult(locationPickerIntent, requestSenderLocationCode);

Above code works when only map is selected

LatLngBounds.Builder builder = new LatLngBounds.Builder();
                builder.include(new LatLng(bottomCoordinate,leftCoordinate)).include(new LatLng(topCoordinate,rightCoordinate));
                LatLngBounds cityBounds=builder.build();
                Intent locationPickerIntent = new VanillaPlacePicker.Builder(OrderActivity.this)
                        .withLocation(cityLatitude,cityLongitude)
                        .with(PickerType.AUTO_COMPLETE)
                        .setPickerLanguage(PickerLanguage.ENGLISH)
                        .setLocationRestriction(cityBounds.southwest,cityBounds.northeast)
                        .setCountry("IN")
                        .enableShowMapAfterSearchResult(true)
                        .setMapType(MapType.NORMAL)
                        .setMapPinDrawable(R.drawable.ic_placeholder)
                        .build();
                startActivityForResult(locationPickerIntent, requestSenderLocationCode);

and this works when using AUTO Complete
Problem is when I type MAP_WITH_AUTO_COMPLETE either search wont work or map wont start!

**Comment by malikmotani** [comment]
The issue seems with the values you are passing here 
`.setLocationRestriction(cityBounds.southwest,cityBounds.northeast)`
Can you please try this?
`.setLocationRestriction(cityBounds.northeast,cityBounds.southwest)`
