### ISSUE TITLE
Automomplete result not getting

### ISSUE THREAD

**Issue by Gurmail89** [Mindinventory/vanilla-place-picker#42]
Hello, 

I'm integrating this awesome library, but unfortunately with MAP_WITH_AUTO_COMPLETE, google auto search fragment open. but when I am searching some places it closed automatically without showing any result. 

Please let me know the solution for this.

Thanks

**Comment by malikmotani** [comment]
Hello @Gurmail89 ,
Make sure your google-services.json is configured properly and you have a working API key for the google places API.
