### ISSUE TITLE
Auto complete not giving  result according to set country  

### ISSUE THREAD

**Issue by hamza11223322** [Mindinventory/vanilla-place-picker#43]
if (vanillaConfig.country.isNullOrBlank()) {
            autocomplete.setCountry(vanillaConfig.country)
      }

May be the issue  in this function 
May be ! sign is missing there 
if (!vanillaConfig.country.isNullOrBlank())

**Comment by malikmotani** [comment]
Thank you @hamza11223322 for identifying the issue, our team will fix this soon and make it available in the next version of the library
