### ISSUE TITLE
On Activity Result gives me a different coordinates from the ones i did select on the map

### ISSUE THREAD

**Issue by MahmoudiOussama** [Mindinventory/vanilla-place-picker#45]
Hi all, I love this library and its features, have been using it for a while now.
I recently noticed something weird! If I select a location where there is no road, I will get different coordinates within the onActivityResult function, those coordinates are in the nearest road from the selected ones.

Have you implemented this feature on purpose?

**Comment by akashmi** [comment]
@MahmoudiOussama we have not implemented any feature like that.
it might be issue with location accuracy. still we will look into your issue in details.
if you found solution then please create PR for that. your contribution will be always appreciated.
Thanks for using this library. :)

**Comment by MahmoudiOussama** [comment]
@akashmi Thank you for answering, can you please point me to the part of code where you extract coordinates from google map (latitude and longitude) ?

Here a screen recording to show you what I wanted to say by this issue : 
  * Iam using a food delivery Android app (MenuTium) where the client should select his delivery location.
  * Iam also using a delivery manager web app, used to manage received food orders, here there is a big map where to show the stores and clients location.

![MenuTium location coordinates error](https://user-images.githubusercontent.com/25067744/117127264-c7464100-ad93-11eb-930c-cc665404f96b.gif)

**Comment by akashmi** [comment]
@MahmoudiOussama You can see below path to get code location.

[https://github.com/Mindinventory/vanilla-place-picker/blob/master/vanillaplacepicker/src/main/java/com/vanillaplacepicker/presentation/map/VanillaMapActivity.kt](https://github.com/Mindinventory/vanilla-place-picker/blob/master/vanillaplacepicker/src/main/java/com/vanillaplacepicker/presentation/map/VanillaMapActivity.kt)

**Comment by HassanAhamd** [comment]
hi Bro 
AutoComplete is not working properly when i try to enter my adress i start typing it did not get the location and send that my typed string via intent...

**Comment by chiragmi** [comment]
Hello @MahmoudiOussama 
Thanks for using the library.

![Screenshot from 2021-08-31 17-54-52](https://user-images.githubusercontent.com/87471481/131845237-2bf0b1b2-06ef-4b90-8ed3-897f43e835d3.png)


![Screenshot from 2021-08-31 17-55-16](https://user-images.githubusercontent.com/87471481/131845268-d79075f0-87be-4698-ae25-fcf4a7084737.png)


![Screenshot from 2021-09-02 17-42-11](https://user-images.githubusercontent.com/87471481/131845286-cd243bcb-149b-4a1d-ba8b-54fefb184e96.png)

Kindly take a reference to the attached screenshots. As you can see, selected “Turnkey Tracking Company” by marker from the library and got **latitude: 35.8203366** and **longitude: 10.5918915** which is approx. same as shown by Google Maps. It may be possible that you’re trying to get LAT-LNG from an address and are not returning correct values.
