### ISSUE TITLE
When i vanillaPlacePickerType.AutoComplete  when i try to enter any place name it did not get that location after typing single charater its send that charater as a place and my app crash because my intent need a place and it found a string AUTOCOMPLETE ant Solution plz 

### ISSUE THREAD

**Issue by HassanAhamd** [Mindinventory/vanilla-place-picker#46]

**Comment by akashmi** [comment]
@HassanAhamd Can you please share more details with error message and video?

**Comment by akashmi** [comment]
@HassanAhamd seems like you are not using a valid Google API key or didn't enable place API or didn't set up an account to access place APIs.

Please feel free to open issue, if you still getting an error after applying/verifying provided solutions.
