### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Irfanhaidermomin** [Mindinventory/vanilla-place-picker#57]
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.SettingsClient, but class was expected (declaration of 'com.google.android.gms.location.SettingsClient' appears in base.apk)

**Comment by Irfanhaidermomin** [comment]
I think you should resolve by updating this service
**com.google.android.gms:play-services-location:21.0.1**

Please try and update this ASAP.

**Comment by chiragmi** [comment]
@Irfanhaidermomin 
Yes, We have found this issue and resolved that. We'll launch resolved version soon.
Thanks.

**Comment by chiragmi** [comment]
Hello @Irfanhaidermomin  

Thank you for using the VanillaPlacePicker Library.

We have released a new version 0.3.1 with resolved this issue.

Please try it out and let us know in case have any issues.

Thank you
